# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_remove_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='creat_time',
        ),
    ]
