# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-26 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_remove_tag_creat_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
